apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: pi
          image: gcr.io/MY_PROJECT/generate-pi:latest
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 1Gi
          imagePullPolicy: IfNotPresent
      restartPolicy: Never