
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  parallelism: 1
  template:
    metadata:
      name: simple-job
      labels:
        app: simple-app
    spec:
      serviceAccountName: ksa
      containers:
        - name: pi
          image: eu.gcr.io/jtg-firebase-dev102/generate-pi:latest
          resources:
            limits:
              cpu: 0.5
              memory: 2Gi
            requests:
              cpu: 0.5
              memory: 2Gi
          imagePullPolicy: IfNotPresent
      restartPolicy: Never