apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  template:
    spec:
      serviceAccountName: tenant1-ksa
      containers:
        - name: pi
          args:
            - --bucket=MY_BUCKET
