apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  template:
    spec:
      containers:
        - name: pi
          resources:
            limits:
              cpu: 1.0
              memory: 2Gi
            requests:
              cpu: 1.0
              memory: 2Gi
