apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  template:
    spec:
      nodeSelector:
        tenant: tenant1
      tolerations:
      - key: tenant
        operator: Equal
        value: tenant1
        effect: NoSchedule
